name: oceanpy-env

channels:
  - conda-forge
  # - http://ssb.stsci.edu/astroconda

dependencies:
  - python=3.6
  - xarray
  - numpy
  - pyproj
  - netCDF4
  - scipy
  - gsw
  - sphinx
  # - pandoc
  # - nbconvert
  # - ipykernel
  - nbsphinx
  - pandoc
  - pip

  # - stsci.convolve
