name: oceanpy-env

channels:
    - conda-forge
    - stsci

dependencies:
  - python=3.6
  - pip
  - pip:
    - stsci.convolve
  - xarray
  - numpy
  - pyproj
  - netCDF4
  - scipy
  - stsci.convolve
  - gsw
