name: oceanpy-env

channels:
  - conda-forge
  # - http://ssb.stsci.edu/astroconda

dependencies:
  - python>=3.6
  - numpy
  - pyproj
  - netCDF4
  - scipy
  - gsw
  - xarray
  - dask
  - xgcm
  - scikit-image
  - ffmpeg
  # - nbconvert
  # - ipykernel
  - sphinx
  - nbsphinx
  - pandoc
  - pip

  # - stsci.convolve
